export const projectsList = [
  {
    id: 1,
    name: "AREA",
    description:
      "Website Pittsburgh.",
    image: "/images/secret_pittsburgh.png",
    mobileImage: "/images/secret_pittsburgh_small.png",
    link: "https://github.com/TheoParamelle/my_area",
    GitHub: "https://github.com/TheoParamelle/my_area",
    project: "area",
    tools: ["React Native", "Python", "Expo go, Docker"],
  },
  {
    id: 2,
    name: "R-type",
    description:
      "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "r-type",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  },
  {
    id: 3,
    name: "Angel",
    description:
        "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "angel",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  },
  {
    id: 4,
    name: "Trading bot",
    description:
        "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "pollock-is-shit",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  },
  {
    id: 5,
    name: "Gomoku",
    description:
        "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "pollock-is-shit",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  },
  {
    id: 6,
    name: "MinilibC",
    description:
        "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "pollock-is-shit",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  },
  {
    id: 6,
    name: "Jetpack2tek3",
    description:
        "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "pollock-is-shit",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  },
  {
    id: 6,
    name: "AbstractVM",
    description:
        "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "pollock-is-shit",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  },
  {
    id: 7,
    name: "Sophro-Diet-Consult",
    description:
        "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "pollock-is-shit",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  },
  {
    id: 8,
    name: "Portfolio personnel",
    description:
        "Web app that manipulates image data to create a Pollock-like painting (because literally anyone could've been Pollock).",
    image: "/images/Pollock_Is_Shit_Screenshot.png",
    mobileImage: "/images/Pollock_is_Shit_OG.png",
    link: "https://pollockisshit.netlify.app/",
    GitHub: "https://github.com/GameDog9988/Pollock-is-Poop",
    project: "pollock-is-shit",
    tools: ["React/Next.js", "Tailwind CSS", "p5.js"],
  }
];
