export const projectsList = [
  {
    id: 1,
    name: "Area",
    description:
      "Business application that connects services to automate tasks between them",
    image: "/images/area.png",
    mobileImage: "/images/area_small.png",
    link: "https://github.com/TheoParamelle/my_area",
    GitHub: "https://github.com/TheoParamelle/my_area",
    project: "area",
    tools: ["React Native", "Python", "Expo go, Docker"],
  },
  {
    id: 2,
    name: "Portfolio",
    description:
        "My portfolio website",
    image: "/images/portfolio.png",
    mobileImage: "/images/portfolio_small.png",
    link: "https://portfolio-theoparamelle.vercel.app",
    GitHub: "https://github.com/TheoParamelle/portfolio",
    project: "portfolio",
    tools: ["JS", "CSS"],
  },
  {
    id: 3,
    name: "R-type",
    description:
      "This project aims to recreate the R-Type game and add a multiplayer mode to it. We had to implement a multi-threaded server using Boost and a graphical client in SFML",
    image: "/images/r_type.png",
    mobileImage: "/images/r_type_small.png",
    link: "https://github.com/TheoParamelle/my_r_type",
    GitHub: "https://github.com/TheoParamelle/my_r_type",
    project: "r-type",
    tools: ["C++", "SFML", "Boost C++"],
  },
  {
    id: 4,
    name: "Angel",
    description:
        "EIP project, application against street resentment, you can see the showcase site of our project",
    image: "/images/angel.png",
    mobileImage: "/images/angel_small.png",
    link: "https://angel-the-guardian.vercel.app",
    GitHub: "https://github.com/TheoParamelle/EIP-web-page/tree/gh-pages",
    project: "angel",
    tools: ["React Native, Python, Docker for the application", "HTML, JS, CSS for showcase site"],
  },
  {
    id: 5,
    name: "Trading bot",
    description:
        "The goal of this project is to create a bot that buys different currencies considering the current market prices. This bot will be tested using the program ai-bot-workspace",
    image: "/images/trading_bot.png",
    mobileImage: "/images/trading_bot_small.png",
    link: "https://github.com/TheoParamelle/trading_bot",
    GitHub: "https://github.com/TheoParamelle/trading_bot",
    project: "trading-bot",
    tools: ["Java"],
  },
  {
    id: 6,
    name: "Gomoku",
    description:
        "The goal of this project is to implement a Gomoku Narabe game bot (also called Wuzi Qi, Slope, Darpion or Five in a Row), focusing on the performance of its artificial intelligence (Min-Max algorithm)",
    image: "/images/gomoku.png",
    mobileImage: "/images/gomoku_small.png",
    link: "https://github.com/TheoParamelle/gomoku",
    GitHub: "https://github.com/TheoParamelle/gomoku",
    project: "gomoku",
    tools: ["Python", "Piskvork"],
  },
  {
    id: 7,
    name: "Sophro-Diet-Consult",
    description:
        "Website develop with a an editor, Performance monitoring with Google Analytics, SEO optimization, and training of staff on different software",
    image: "/images/sophro_diet.png",
    mobileImage: "/images/sophro_diet_small.png",
    link: "https://sophro-diet-consult.com",
    GitHub: "https://github.com/TheoParamelle",
    project: "sophro-diet",
    tools: ["HTML", "CSS"],
  },
  {
    id: 8,
    name: "MinilibC",
    description:
        "create a dynamic ELF library to replace (to a certain extent) the standard C library you use every day on your system",
    image: "/images/minilibc.png",
    mobileImage: "/images/minilibc_small.png",
    link: "https://github.com/TheoParamelle/libC",
    GitHub: "https://github.com/TheoParamelle/libC",
    project: "libc",
    tools: ["Assembly", "Makefile"],
  },
  {
    id: 9,
    name: "Jetpack2tek3",
    description:
        "The goal of this project is to create a game like Jetpack Joyride. There are two parts: the game server and the client program",
    image: "/images/jetpack2tek3.png",
    mobileImage: "/images/jetpack2tek3_small.png",
    link: "https://github.com/TheoParamelle/jetpack",
    GitHub: "https://github.com/TheoParamelle/jetpack",
    project: "jetpack2tek3",
    tools: ["C", "CSFML", "pthread"],
  },
  {
    id: 10,
    name: "AbstractVM",
    description:
        "The goal of this project is to create a simple virtual machine that is able to interpret programs that are written in a simplified assembler language",
    image: "/images/abstract_vm.png",
    mobileImage: "/images/abstract_vm_small.png",
    link: "https://github.com/TheoParamelle/abstractvm",
    GitHub: "https://github.com/TheoParamelle/abstractvm",
    project: "abstract",
    tools: ["C++", "Makefile"],
  }
];
